import type { Metadata } from "next";
import "@/styles/web.css";
import { ThemeProvider } from "next-themes";
import Header from "@/components/layout/Header";

export const metadata: Metadata = {
    title: "Eulji | Lightweight CRM System",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" suppressHydrationWarning>
            <body>
                <ThemeProvider>
                    <div className="flex justify-center items-center pt-(--header-height)">{children}</div>
                </ThemeProvider>
            </body>
        </html>
    );
}
