import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import QueryProvider from "@/components/QueryProvider";

export const metadata: Metadata = {
    title: "Eulji | Lightweight CRM System",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko" suppressHydrationWarning>
            <body>
                <ThemeProvider>
                    <div className="flex h-screen w-full bg-(--background)">
                        {children}
                    </div>
                </ThemeProvider>
            </body>
        </html>
    );
}
