import type { Metadata } from "next";
import "@/styles/dashboard.css";
import { ThemeProvider } from "next-themes";
import QueryProvider from "@/components/providers/QueryProvider";
import { createSupabaseServerClient } from "@/lib/supabase/server";
import { redirect } from "next/navigation";
import { syncAuthenticatedUser } from "@/lib/auth/service";


export const metadata: Metadata = {
    title: "Eulji | Lightweight CRM System",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const supabase = await createSupabaseServerClient();
    const {
        data: { user },
    } = await supabase.auth.getUser();
    if (!user) {
        redirect("/auth/login");
    }

    await syncAuthenticatedUser(user);

    return (
        <html lang="ko" suppressHydrationWarning>
            <body>
                <ThemeProvider>
                    <QueryProvider>
                        <div className="flex h-screen w-full bg-(--background)">
                            {children}
                        </div>
                    </QueryProvider>
                </ThemeProvider>
            </body>
        </html>
    );
}
